"""Databricks Asset Bundle (DAB) generator.

Generates a complete DAB project structure:
  databricks.yml
  resources/<name>_job.yml
  src/<name>.py
  environments/{dev,staging,prod}.yml
"""

from __future__ import annotations

import logging

from a2d.config import ConversionConfig
from a2d.generators.base import GeneratedFile, GeneratedOutput
from a2d.ir.graph import WorkflowDAG

logger = logging.getLogger("a2d.generators.dab")


class DABGenerator:
    """Generate Databricks Asset Bundle project files."""

    def __init__(self, config: ConversionConfig) -> None:
        self.config = config

    def generate(self, dag: WorkflowDAG, workflow_name: str, output: GeneratedOutput) -> list[GeneratedFile]:
        """Generate DAB project files."""
        files: list[GeneratedFile] = []

        # 1. Main databricks.yml
        files.append(self._generate_databricks_yml(workflow_name))

        # 3. Source file (copy the main generated code). Its type drives the task
        #    kind below: SQL must not be run as a Spark Python task.
        main_code, is_sql = self._find_main_code(output)

        # 2. Job resource definition (task type matches the source file type)
        files.append(self._generate_job_yml(workflow_name, is_sql=is_sql))

        if main_code:
            ext = "sql" if is_sql else "py"
            files.append(
                GeneratedFile(
                    filename=f"src/{workflow_name}.{ext}",
                    content=main_code,
                    file_type="sql" if is_sql else "python",
                )
            )

        # 4. Environment configs
        for env in ("dev", "staging", "prod"):
            files.append(self._generate_env_yml(workflow_name, env))

        return files

    def _generate_databricks_yml(self, workflow_name: str) -> GeneratedFile:
        """Generate the main databricks.yml bundle config."""
        content = f"""# Databricks Asset Bundle configuration
# Generated by a2d — review and customize before deployment

bundle:
  name: {workflow_name}_migration

include:
  - resources/*.yml
  - environments/*.yml

workspace:
  root_path: /Workspace/Users/${{workspace.current_user.userName}}/{workflow_name}
"""
        return GeneratedFile(
            filename="databricks.yml",
            content=content,
            file_type="yaml",
        )

    def _generate_job_yml(self, workflow_name: str, *, is_sql: bool = False) -> GeneratedFile:
        """Generate the job resource YAML.

        A PySpark source runs as a ``spark_python_task`` on a job cluster, using
        ``job_clusters[]`` + ``job_cluster_key: main`` indirection (matches the
        Workflow JSON generator, so the cluster spec lives in one place).

        A SQL source runs as a ``sql_task`` on a SQL warehouse instead: it does
        not use a job cluster, so no ``job_clusters`` block is emitted for it.

        ``spark_version`` is the Databricks Runtime key (``<dbr>.x-scala2.12``),
        not the bare Apache Spark version — a raw ``"3.5"`` is not a valid cluster
        runtime and fails cluster creation. ``node_type_id`` is selected from
        :data:`a2d.config.CLOUD_NODE_TYPE_IDS` based on ``ConversionConfig.cloud``.
        """
        catalog = self.config.catalog_name
        schema = self.config.schema_name
        # Databricks Runtime key, e.g. "14.3.x-scala2.12" (not the Spark version).
        runtime_version = f"{self.config.dbr_version}.x-scala2.12"

        header = f"""# Job definition for {workflow_name}
# Generated by a2d — review and customize before deployment

resources:
  jobs:
    {workflow_name}_job:
      name: "{workflow_name}"
      schedule:
        quartz_cron_expression: "0 0 8 * * ?"
        timezone_id: "UTC"
"""
        if is_sql:
            # SQL runs on a warehouse; no job cluster.
            body = f"""
      tasks:
        - task_key: "run_{workflow_name}"
          sql_task:
            # Set the target SQL warehouse before deploying.
            warehouse_id: "${{var.warehouse_id}}"
            file:
              path: ../src/{workflow_name}.sql
"""
        else:
            # Cloud-aware worker SKU. Defaults to AWS (i3.xlarge); override via
            # `--cloud azure` (Standard_DS3_v2) or `--cloud gcp` (n1-highmem-4).
            node_type_id = self.config.node_type_id
            body = f"""
      job_clusters:
        - job_cluster_key: "main"
          new_cluster:
            spark_version: "{runtime_version}"
            num_workers: 2
            # Cloud-specific worker SKU (cloud="{self.config.cloud}").
            node_type_id: "{node_type_id}"

      tasks:
        - task_key: "run_{workflow_name}"
          job_cluster_key: "main"
          spark_python_task:
            python_file: ../src/{workflow_name}.py
"""

        footer = f"""
      parameters:
        - name: "catalog"
          default: "{catalog}"
        - name: "schema"
          default: "{schema}"

      tags:
        source: "alteryx_migration"
        tool: "a2d"
"""
        return GeneratedFile(
            filename=f"resources/{workflow_name}_job.yml",
            content=header + body + footer,
            file_type="yaml",
        )

    def _generate_env_yml(self, workflow_name: str, env: str) -> GeneratedFile:
        """Generate environment-specific config."""
        catalog = self.config.catalog_name
        schema = self.config.schema_name

        # Adjust for environment
        env_catalog = f"{catalog}_{env}" if env != "prod" else catalog
        workers = {"dev": 1, "staging": 2, "prod": 4}.get(env, 2)

        content = f"""# {env.capitalize()} environment configuration
# Generated by a2d

targets:
  {env}:
    mode: {"development" if env == "dev" else "production"}
    default: {str(env == "dev").lower()}
    workspace:
      host: ${{var.{env}_workspace_host}}

    variables:
      catalog: "{env_catalog}"
      schema: "{schema}"
      num_workers: {workers}
"""
        return GeneratedFile(
            filename=f"environments/{env}.yml",
            content=content,
            file_type="yaml",
        )

    @staticmethod
    def _find_main_code(output: GeneratedOutput) -> tuple[str | None, bool]:
        """Find the main code file. Returns ``(content, is_sql)``.

        Prefers a Python file; falls back to SQL. ``is_sql`` tells the job
        generator to emit a ``sql_task`` (on a warehouse) instead of a
        ``spark_python_task`` — SQL text is not valid Python.
        """
        sql_content: str | None = None
        for f in output.files:
            if f.filename.endswith(".json"):
                continue
            if f.file_type == "python":
                return f.content, False
            if f.file_type == "sql" and sql_content is None:
                sql_content = f.content
        if sql_content is not None:
            return sql_content, True
        return None, False
